services:
  - type: web
    name: healthcare
    runtime: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr && \
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
